### ISSUE TITLE
Examples and other practice here

### ISSUE THREAD

**Issue by drenn2** [bowers-grad-stats-illinois/dailyR#1]
@bowers-grad-stats-illinois/530-students , please check this repository for some examples and mini-workshops that should help with dailyR. Do the first one (Rmarkdown) at the minimum to make sure that you can compile to html.

**Comment by rjagosto** [comment]
Jason!! I fixed all the codes but how can I do the pull request??

Rebeca J. Agosto Rosa
Ph.D. Student
Department of Political Science
rja2@illinois.edu<mailto:rja2@illinois.edu>

On Aug 31, 2016, at 11:40 AM, Jason Renn <notifications@github.com<mailto:notifications@github.com>> wrote:


@bowers-grad-stats-illinois/530-students<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_orgs_bowers-2Dgrad-2Dstats-2Dillinois_teams_530-2Dstudents&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=KeYTjg6hBW4GPN79yUFERvrkS5HGKm_QZYiQFeT7KjA&m=M26qJ7EaWOLe3t5tIhM-hih3dbhZfxL66gW4uLFosHc&s=UJXAwFH7zbPAhTphIChDwiUbHP4Eke626MLMhrYBjGQ&e=> , please check this repository for some examples and mini-workshops that should help with dailyR. Do the first one (Rmarkdown) at the minimum to make sure that you can compile to html.
